# Generated by Django 5.2.3 on 2025-07-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='rating',
        ),
        migrations.AddField(
            model_name='quote',
            name='negative_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='positive_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='weighted_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QuoteRating',
        ),
    ]
