# Generated by Django 5.2.3 on 2025-07-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteWebsite', '0002_remove_quote_rating_quote_negative_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='weighted_rating',
        ),
        migrations.AddField(
            model_name='quote',
            name='total_rating',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='negative_rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='positive_rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_weight',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='quotesource',
            name='quote_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
