# Generated by Django 5.2.3 on 2025-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteWebsite', '0003_remove_quote_weighted_rating_quote_total_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesource',
            name='author',
            field=models.CharField(default='Надо будет удалить', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotesource',
            name='publishment_date',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
