# Generated by Django 5.2.3 on 2025-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteWebsite', '0004_alter_quotesource_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageviews',
            name='name',
            field=models.CharField(default='views'),
        ),
    ]
