# Generated by Django 5.2.3 on 2025-07-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteWebsite', '0005_pageviews_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviews',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
